### ISSUE TITLE
Unlicensed

### ISSUE THREAD

**Issue by Frederik-Levesque** [ProtocolNebula/HTML-Signature-Generator-Boilerplate-JS#14]
It's really a good idea and would be very useful for us. However, since there is no explicit license in the project, we don’t want to transgress any copyright.

The default license for GitHub is “All rights reserved”:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

If your intention is to share this work, I was wondering if you could add a license to the git repo that grants the right to use, modify, and distribute this boilerplate?

The MIT license could be an option to consider:
https://choosealicense.com/licenses/mit/

Thank you very much for your work.

**Comment by ProtocolNebula** [comment]
Hello,
Sorry for late reply.

I forgot to put license the time I've created the repository.


Later I'll look for the correct license, I'm not sure yet if to just use MIT.
You can use the code as you wish.

Best regards.
________________________________
De: Frédérik Lévesque ***@***.***>
Enviado: miércoles, 17 de julio de 2024 22:09
Para: ProtocolNebula/HTML-Signature-Generator-Boilerplate-JS ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [ProtocolNebula/HTML-Signature-Generator-Boilerplate-JS] Unlicensed (Issue #14)


It's really a good idea and would be very useful for us. However, since there is no explicit license in the project, we don’t want to transgress any copyright.

The default license for GitHub is “All rights reserved”:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

If your intention is to share this work, I was wondering if you could add a license to the git repo that grants the right to use, modify, and distribute this boilerplate?

The MIT license could be an option to consider:
https://choosealicense.com/licenses/mit/

Thank you very much for your work.

**Comment by Frederik-Levesque** [comment]
Thank you so much! I'm looking forward to seeing the license change.

**Comment by ProtocolNebula** [comment]
Added MIT license.
